[package]
name = "simple-chatting"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.4", features = ["full"] }
aho-corasick = "1.1.3"
warp = "0.3"
futures-util = "0.3.30"
lazy_static = "1.5.0"